CREATE TABLE [sales].[salesorderheader] (

	[SalesOrderID] int NULL, 
	[RevisionNumber] smallint NULL, 
	[OrderDate] datetime2(6) NULL, 
	[DueDate] datetime2(6) NULL, 
	[ShipDate] datetime2(6) NULL, 
	[Status] smallint NULL, 
	[OnlineOrderFlag] bit NULL, 
	[SalesOrderNumber] varchar(8000) NULL, 
	[PurchaseOrderNumber] varchar(8000) NULL, 
	[AccountNumber] varchar(8000) NULL, 
	[CustomerID] int NULL, 
	[SalesPersonID] int NULL, 
	[TerritoryID] int NULL, 
	[BillToAddressID] int NULL, 
	[ShipToAddressID] int NULL, 
	[ShipMethodID] int NULL, 
	[CreditCardID] int NULL, 
	[CreditCardApprovalCode] varchar(8000) NULL, 
	[CurrencyRateID] int NULL, 
	[SubTotal] decimal(19,4) NULL, 
	[TaxAmt] decimal(19,4) NULL, 
	[Freight] decimal(19,4) NULL, 
	[TotalDue] decimal(19,4) NULL, 
	[Comment] varchar(8000) NULL, 
	[rowguid] varchar(8000) NULL, 
	[ModifiedDate] datetime2(6) NULL
);

