CREATE TABLE [CTRL].[FABRIC_METADATA_test] (

	[SOURCE_SYSTEM] varchar(100) NOT NULL, 
	[LH_NAME] varchar(100) NOT NULL, 
	[SOURCE_SCHEMA] varchar(100) NOT NULL, 
	[SOURCE_TABLE] varchar(100) NOT NULL, 
	[DESTINATION_TABLE] varchar(100) NOT NULL, 
	[TABLE_TYPE] varchar(100) NOT NULL, 
	[PRIMARY_KEY] varchar(100) NOT NULL, 
	[LOADING_METHOD] varchar(100) NOT NULL, 
	[ACTIVE] int NOT NULL, 
	[FREQUENCY] varchar(2) NOT NULL, 
	[VERSION] datetime2(6) NOT NULL
);

